import type { SubcontractorWrapSheet } from "./command-map-types";

export const INITIAL_COMMAND_MAP_SUBCONTRACTORS: SubcontractorWrapSheet[] = [
  {
    id: "sub-atl-ironworks",
    companyName: "Peachtree Ironworks & Gate",
    contactName: "Marcus Hill",
    phone: "(404) 555-0198",
    email: "dispatch@peachtreeironworks.example",
    website: "https://peachtreeironworks.example",
    location: { city: "Atlanta", state: "GA", lat: 33.749, lng: -84.388 },
    service_radius: 125,
    skills: ["Custom Ironwork", "Automation Gates", "Welding"],
    activeCities: ["Atlanta", "Marietta", "Athens", "Macon"],
    pricingTier: "$175/hr welding, $425 emergency flat rate",
    waitsForPayout: true,
    notes: "Strong overnight response for retail centers. Prefers dispatch text plus email scope.",
    historicalPerformance: "18 completed jobs, 4.7 quality score, one callback in Q1.",
    source: "network",
  },
  {
    id: "sub-atl-privacy",
    companyName: "North Metro Fence Pros",
    contactName: "Alicia Nguyen",
    phone: "(678) 555-0124",
    email: "ops@northmetrofence.example",
    location: { city: "Marietta", state: "GA", lat: 33.9526, lng: -84.5499 },
    service_radius: 75,
    skills: ["Wood Privacy", "Chain Link", "Facilities Maintenance"],
    activeCities: ["Marietta", "Atlanta", "Roswell"],
    pricingTier: "$95/hr crew rate, materials plus 18%",
    waitsForPayout: false,
    notes: "Best fit for multi-site privacy fence repairs and fast gate rehanging.",
    historicalPerformance: "9 completed jobs, consistently sends same-day photos.",
    source: "network",
  },
  {
    id: "sub-la-gulf",
    companyName: "Gulf State Weld & Fence",
    contactName: "Trey Broussard",
    phone: "(504) 555-0151",
    email: "trey@gulfstateweld.example",
    location: { city: "New Orleans", state: "LA", lat: 29.9511, lng: -90.0715 },
    service_radius: 150,
    skills: ["Welding", "Bollards", "Security Grille"],
    activeCities: ["New Orleans", "Baton Rouge", "Houma"],
    pricingTier: "$155/hr welding, $375 emergency flat rate",
    waitsForPayout: true,
    notes: "Good for corrosion-heavy coastal work; ask for photos before authorizing paint.",
    historicalPerformance: "22 completed jobs, excellent night dispatch availability.",
    source: "network",
  },
  {
    id: "sub-ms-capitol",
    companyName: "Capitol City Gate Service",
    contactName: "Denise Carter",
    phone: "(601) 555-0177",
    email: "service@capitolcitygate.example",
    location: { city: "Jackson", state: "MS", lat: 32.2988, lng: -90.1848 },
    service_radius: 200,
    skills: ["Automation Gates", "Fence", "Access Control"],
    activeCities: ["Jackson", "Meridian", "Hattiesburg", "Vicksburg"],
    pricingTier: "$135/hr tech rate, $250 diagnostic",
    waitsForPayout: false,
    notes: "Reliable with retail chain paperwork and before/after closeout packets.",
    historicalPerformance: "31 completed jobs, 4.8 response score.",
    source: "network",
  },
  {
    id: "sub-al-steel",
    companyName: "Magic City Steel Repair",
    contactName: "Andre Wilson",
    phone: "(205) 555-0142",
    email: "andre@magiccitysteel.example",
    location: { city: "Birmingham", state: "AL", lat: 33.5186, lng: -86.8104 },
    service_radius: 110,
    skills: ["Custom Ironwork", "Welding", "Bollards"],
    activeCities: ["Birmingham", "Tuscaloosa", "Montgomery"],
    pricingTier: "$165/hr welding, $500 after-hours minimum",
    waitsForPayout: true,
    notes: "Great for bollard resets and steel plate repair; needs clear NTE approval.",
    historicalPerformance: "14 completed jobs, no callbacks in last 12 months.",
    source: "network",
  },
  {
    id: "sub-ar-ozark",
    companyName: "Ozark Perimeter Solutions",
    contactName: "Hannah Price",
    phone: "(479) 555-0119",
    email: "dispatch@ozarkperimeter.example",
    location: { city: "Fayetteville", state: "AR", lat: 36.0626, lng: -94.1574 },
    service_radius: 175,
    skills: ["Chain Link", "Commercial Fence", "Gate"],
    activeCities: ["Fayetteville", "Fort Smith", "Little Rock"],
    pricingTier: "$120/hr crew rate, $325 emergency flat rate",
    waitsForPayout: false,
    notes: "Handles long rural runs without mileage disputes if routed two days ahead.",
    historicalPerformance: "16 completed jobs, strongest Arkansas coverage.",
    source: "network",
  },
  {
    id: "sub-ks-prairie",
    companyName: "Prairie Gate Automation",
    contactName: "Chris Patel",
    phone: "(316) 555-0108",
    email: "chris@prairiegateautomation.example",
    location: { city: "Wichita", state: "KS", lat: 37.6872, lng: -97.3301 },
    service_radius: 220,
    skills: ["Automation Gates", "Access Control", "Welding"],
    activeCities: ["Wichita", "Topeka", "Kansas City"],
    pricingTier: "$145/hr tech rate, parts plus 20%",
    waitsForPayout: true,
    notes: "Preferred for controller diagnostics; confirm gate brand before dispatch.",
    historicalPerformance: "11 completed jobs, fast quote turnaround.",
    source: "network",
  },
  {
    id: "sub-mo-riverfront",
    companyName: "Riverfront Fence & Weld",
    contactName: "Leah Martin",
    phone: "(314) 555-0133",
    email: "leah@riverfrontfence.example",
    location: { city: "St. Louis", state: "MO", lat: 38.627, lng: -90.1994 },
    service_radius: 160,
    skills: ["Security Grille", "Welding", "Facilities Maintenance"],
    activeCities: ["St. Louis", "Columbia", "Springfield"],
    pricingTier: "$150/hr labor, $400 emergency flat rate",
    waitsForPayout: false,
    notes: "Good paperwork and COI turnaround. Keep on interior security grille repairs.",
    historicalPerformance: "19 completed jobs, two emergency saves under NTE.",
    source: "network",
  },
  {
    id: "sub-tn-volunteer",
    companyName: "Volunteer Commercial Fence",
    contactName: "Raymond Scott",
    phone: "(615) 555-0165",
    email: "ray@volunteercommercial.example",
    location: { city: "Nashville", state: "TN", lat: 36.1627, lng: -86.7816 },
    service_radius: 140,
    skills: ["Commercial Fence", "Wood Privacy", "Gate"],
    activeCities: ["Nashville", "Murfreesboro", "Clarksville"],
    pricingTier: "$115/hr crew rate, $300 emergency flat rate",
    waitsForPayout: true,
    notes: "Strong retail curb appeal work; use for privacy and ornamental fence touch-ups.",
    historicalPerformance: "24 completed jobs, 4.6 quality score.",
    source: "network",
  },
];
